server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor_empleo
    username: gestor
    password: gestor
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
